<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>chartgen</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="PuppeteerSharp" Version="25.0.4" />
  </ItemGroup>
</Project>
